<?php

/**
 *    Copyright (C) 2015 Deciso B.V.
 *
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * Language support, autogenerated file
 *
 */
echo gettext('Diagnostics: Logs: L2TP');
echo gettext('Diagnostics: Logs: PPPoE');
echo gettext('Diagnostics: Logs: PPTP');
echo gettext('Lobby: Hello World!');
echo gettext('Services: FTP Proxy');
echo gettext('Services: HAProxy');
echo gettext('Services: PPPoE Server');
echo gettext('Services: PPPoE Server: Edit');
echo gettext('Services: SMART');
echo gettext('Services: Web Proxy: SSO');
echo gettext('VPN: L2TP');
echo gettext('VPN: L2TP: Users');
echo gettext('VPN: L2TP: Users: Edit');
echo gettext('VPN: PPTP');
echo gettext('VPN: PPTP: User: Edit');
echo gettext('VPN: PPTP: Users');
echo gettext('VPN: Tinc configuration');
echo gettext('WebCfg - Diagnostics: ARP Table page');
echo gettext('WebCfg - Diagnostics: Netflow configuration');
echo gettext('WebCfg - Diagnostics: Network Insight');
echo gettext('WebCfg - Diagnostics: Routing tables page');
echo gettext('WebCfg - Diagnostics: System Activity');
echo gettext('WebCfg - Diagnostics: System Health');
echo gettext('WebCfg - Firewall: Traffic Shaper page');
echo gettext('WebCfg - Load Balancer: Pool page');
echo gettext('WebCfg - Load Balancer: Pool: Edit page');
echo gettext('WebCfg - Load Balancer: Virtual Server: Edit page');
echo gettext('WebCfg - Service: Universal Plug and Play page');
echo gettext('WebCfg - Services: Captive Portal');
echo gettext('WebCfg - Services: Intrusion Detection page');
echo gettext('WebCfg - Services: Load Balancer: Monitor: Edit page');
echo gettext('WebCfg - Services: Load Balancer: Monitors page');
echo gettext('WebCfg - Services: Load Balancer: Virtual Servers page');
echo gettext('WebCfg - Services: Load Balancer: setting page');
echo gettext('WebCfg - Services: Proxy page');
echo gettext('WebCfg - Status: Load Balancer: Pool page');
echo gettext('WebCfg - Status: Load Balancer: Virtual Server page');
echo gettext('WebCfg - Status: System logs: Load Balancer page');
echo gettext('WebCfg - Status: Universal Plug and Play page');
echo gettext('WebCfg - System: Settings: Cron page');
echo gettext('WebCfg - System: Settings: Syslog page');
echo gettext('Webcfg - Diagnostics: NDP Table page');
