<?php

/**
 *    Copyright (C) 2015 Deciso B.V.
 *
 *    All rights reserved.
 *
 *    Redistribution and use in source and binary forms, with or without
 *    modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 *    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 *    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *    POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * Language support, autogenerated file
 *
 */
echo gettext('
                  Create a list of sites which may not be inspected, for example bank sites.<br/>
                  Prefix the domain with a . to accept all subdomains (e.g. .google.com).
                  ');
echo gettext('
                  Enable sslbump mode,
                  which makes the proxy act as a man in the middle between the internet and your clients.<br/>
                  Be aware of the security implications before enabling this option.
                  <br/><br/>
                  Transparent HTTP proxy needs to be enabled and you need nat rules to reflect your traffic
                  for this feature to work.<br/>
                  <a href="/firewall_nat_edit.php?template=transparant_proxy&https=1"> Add a new firewall rule </a>
                  ');
echo gettext('
                  Enable transparent proxy mode. You will need a firewall rule to forward traffic from the firewall to the proxy server.
                  You may leave the proxy interfaces empty, but remember to set a valid ACL in that case.
                  <br/>
                  <a href="/firewall_nat_edit.php?template=transparant_proxy"> Add a new firewall rule </a>
                  ');
echo gettext('
                  Select a Certificate Authority to use. To create a CA, go to <a href="/system_camanager.php">CA Manager</a>.
                  ');
echo gettext('(FQ-)CoDel ECN');
echo gettext('(FQ-)CoDel interval');
echo gettext('(FQ-)CoDel target');
echo gettext('Action');
echo gettext('Actions');
echo gettext('Actions (ACLs)');
echo gettext('Add servers to this backend. Use TAB key to complete typing.');
echo gettext('Add some randomness in the check interval between 0 and +/- 50%. A value between 2 and 5 seems to show good results. The default value is 0 (disabled).');
echo gettext('Adjust the server\'s weight relative to other servers.');
echo gettext('Administrator\'s Email');
echo gettext('Advanced SSL options');
echo gettext('Advanced settings');
echo gettext('Agent port');
echo gettext('Alert');
echo gettext('Alert action / sid');
echo gettext('Allow');
echo gettext('Allow HAProxy to automatically raise log level for non-completely successful connections to aid debugging.');
echo gettext('Allow interface subnets');
echo gettext('Allow/Deny taffic');
echo gettext('Allowed MAC addresses');
echo gettext('Allowed SSL ports');
echo gettext('Allowed Subnets');
echo gettext('Allowed addresses');
echo gettext('Allowed destination SSL ports, you may use ranges (ex. 222-226) and add comments with colon (ex. 22:ssh).<br/>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Allowed destination TCP port');
echo gettext('Allowed destination TCP ports, you may use ranges (ex. 222-226) and add comments with colon (ex. 22:ssh).<br/>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Application or service');
echo gettext('Authenticate using');
echo gettext('Authentication Prompt');
echo gettext('Authentication TTL (hours)');
echo gettext('Authentication method');
echo gettext('Authentication processes');
echo gettext('Avoid authentication for addresses and subnets in this list');
echo gettext('Avoid authentication for physical addresses in this list');
echo gettext('Balancing Algorithm');
echo gettext('Banned host IP addresses');
echo gettext('Blacklist');
echo gettext('Blacklist destination domains.<br/>
        You may use a regular expression, use a comma or press Enter for new item.<br/>
        <div class="alert alert-info">
            <b>Examples:</b><br/>
            <b class="text-primary">mydomain.com</b> -> matches on <b>*.mydomain.com</b><br/>
            <b class="text-primary">^https?:\/\/([a-zA-Z]+)\.mydomain\.</b> -> matches on <b>http(s)://textONLY.mydomain.*</b><br/>
            <b class="text-primary">\.gif$</b> -> matches on <b>\*.gif</b> but not on <b class="text-danger">\*.gif\test</b><br/>
            <b class="text-primary">\[0-9]+\.gif$</b> -> matches on <b>\123.gif</b> but not on <b class="text-danger">\test.gif</b><br/>
        </div>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Block browser/user-agents');
echo gettext('Block specific MIME type reply');
echo gettext('Block specific MIME type reply.<br/>
        You may use a regular expression, use a comma or press Enter for new item.<br/>
        <div class="alert alert-info">
            <b>Examples:</b><br/>
            <b class="text-primary">video/flv</b> -> matches on <b>Flash Video</b><br/>
            <b class="text-primary">application/x-javascript</b> -> matches on <b>javascripts</b><br/>
        </div>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Block user-agents.<br/>
        You may use a regular expression, use a comma or press Enter for new item.<br/>
        <div class="alert alert-info">
            <b>Examples:</b><br/>
            <b class="text-primary">^(.)+Macintosh(.)+Firefox/37\.0</b> -> matches on <b>Macintosh version of Firefox revision 37.0</b><br/>
            <b class="text-primary">^Mozilla</b> -> matches on <b>all Mozilla based browsers</b><br/>
        </div>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Buffer size');
echo gettext('By default HAProxy operates in <b>keep-alive</b> mode with regards to persistent connections. Option <b>"http-tunnel"</b> disables any HTTP processing past the first request and the first response. Option <b>"httpclose"</b> configures HAProxy to work in HTTP tunnel mode and check if a "Connection: close" header is already set in each direction, and will add one if missing. Option <b>"http-server-close"</b> enables HTTP connection-close mode on the server side while keeping the ability to support HTTP keep-alive and pipelining on the client side. With Option <b>"forceclose"</b> HAProxy will actively close the outgoing server channel as soon as the server has finished to respond and release some resources earlier.');
echo gettext('CA to use');
echo gettext('Cache size in Megabytes');
echo gettext('Can be specified to filter outgoing messages. By default, all messages are sent. If a level is specified, only messages with a severity at least as important as this level will be sent.');
echo gettext('Capture local');
echo gettext('Certificates');
echo gettext('Change the buffer size (in bytes). Lower values allow more sessions to coexist in the same amount of RAM, and higher values allow some applications with very large cookies to work. The default value is 16384. <br/><div class="text-info"><b>NOTE:</b> It is strongly recommended not to change this from the default value, as very low values will break some services such as statistics, and values larger than default size will increase memory usage, possibly causing the system to run out of memory.</div>');
echo gettext('Change the check buffer size (in bytes). Higher values may help find string or regex patterns in very large pages, though doing so may imply more memory and CPU usage. The default value is 16384.');
echo gettext('Check Interval');
echo gettext('Check interval');
echo gettext('Check type');
echo gettext('Choose a TCP port to be used for the local statistics page. The default value is 8822.');
echo gettext('Choose a request pattern to associate a user to a server. See the <a target="_blank" href="http://cbonte.github.io/haproxy-dconv/configuration-1.6.html#stick on">HAProxy documentation</a> for a full description.<br/><div class="text-info"><b>NOTE:</b> Consider not using this feature in multi-process mode, it can result in random behaviours.</div>');
echo gettext('Choose action');
echo gettext('Choose actions to be included in this backend.');
echo gettext('Choose actions to be included in this frontend.');
echo gettext('Choose an action that should be executed if the condition is true.');
echo gettext('Choose an logical operator to be used to form a condition.');
echo gettext('Choose error files to be included in this backend.');
echo gettext('Choose how to test. By using IF it tests if the condition evaluates to true. If you use UNLESS, the sense of the test is reversed.');
echo gettext('Choose one of the 24 standard syslog facilities. The default value is local0.');
echo gettext('Classtype');
echo gettext('Client Timeout');
echo gettext('Clients will be disconnected after this amount of inactivity. They may log in again immediately, though. Enter 0 to disable idle timeout.');
echo gettext('Clients will be disconnected after this amount of time, regardless of activity. They may log in again immediately, though. Enter 0 to disable hard timeout (not recommended unless an idle timeout is set).');
echo gettext('Collect NetFlow data on this firewall, this will automatically append localhost as NetFlow target. Please keep disabled when using a RAM disk (for size and consistency reasons).');
echo gettext('Command');
echo gettext('Compose expression');
echo gettext('Concurrent user logins');
echo gettext('Conditional parameters');
echo gettext('Configure listen addresses for the statistics page to enable remote access, i.e. 10.0.0.1:8080 or haproxy.example.com:8999. Use TAB key to complete typing a listen address.');
echo gettext('Configure listen addresses for this frontend, i.e. 127.0.0.1:8080 or www.example.com:443. Use TAB key to complete typing a listen address.');
echo gettext('Connection Timeout');
echo gettext('Connections coming from (src) or going to (dst) listed countries, default selects both.');
echo gettext('Content');
echo gettext('Cookie length');
echo gettext('Cookie name');
echo gettext('Cookie name to use for stick table (if appropiate table type is selected).');
echo gettext('Countries to alert or block using GeoIP.');
echo gettext('Custom HTTP check');
echo gettext('Custom options');
echo gettext('Custom template');
echo gettext('DB user');
echo gettext('Day of the month');
echo gettext('Days of the week');
echo gettext('Default Backend');
echo gettext('Default Options TTL');
echo gettext('Default for server');
echo gettext('Default option for all server entries.');
echo gettext('Default ttl');
echo gettext('Define the load balancing algorithm to be used in a backend. See the <a target="_blank" href="http://cbonte.github.io/haproxy-dconv/configuration-1.6.html#balance">HAProxy documentation</a> for a full description.');
echo gettext('Description');
echo gettext('Description for this ACL.');
echo gettext('Description for this Lua script.');
echo gettext('Description for this action.');
echo gettext('Description for this backend.');
echo gettext('Description for this error file.');
echo gettext('Description for this frontend.');
echo gettext('Description for this server.');
echo gettext('Description to identify this pipe.');
echo gettext('Description to identify this zone.');
echo gettext('Destination IP');
echo gettext('Destination port');
echo gettext('Destinations');
echo gettext('Detailed Logging');
echo gettext('Don\'t log normal');
echo gettext('Don\'t log null');
echo gettext('Don\'t use port on server, use the same port as frontend receive. If check enable, require port check in server.');
echo gettext('Dynamic queue creation by source or destination address.
        <li> choose destination here to share the total bandwidth of this pipe among all connected clients. </li>
        <li> choose source to provide all connected clients up to a maximum of this pipe configured bandwidth  </li>
        ');
echo gettext('Egress only');
echo gettext('Email (from)');
echo gettext('Email (to)');
echo gettext('Enable CoDel');
echo gettext('Enable CoDel active queue management');
echo gettext('Enable DNS v4 first');
echo gettext('Enable Deep Packet Inspection');
echo gettext('Enable HAProxy');
echo gettext('Enable HAProxy\'s statistics page.');
echo gettext('Enable HAVP');
echo gettext('Enable ICAP');
echo gettext('Enable Preview');
echo gettext('Enable SSL mode');
echo gettext('Enable SSL offloading');
echo gettext('Enable Transparent HTTP proxy');
echo gettext('Enable Transparent mode');
echo gettext('Enable access logging');
echo gettext('Enable access logging.');
echo gettext('Enable authentication');
echo gettext('Enable insertion of the X-Forwarded-For header to requests sent to servers.');
echo gettext('Enable intrusion detection system.');
echo gettext('Enable local cache (requires service restart)');
echo gettext('Enable or disable HAProxy running as root.<br/><div class="text-info"><b>NOTE:</b> Enabling root could be a security issue but it\'s required by some feature.</div>');
echo gettext('Enable or disable SSL communication with this server.');
echo gettext('Enable or disable collecting & providing separate statistics for each socket.');
echo gettext('Enable or disable health checking.');
echo gettext('Enable or disable logging of connections with no data.');
echo gettext('Enable or disable logging of normal, successful connections.');
echo gettext('Enable or disable session redistribution in case of connection failure.');
echo gettext('Enable or disable the HAProxy service.');
echo gettext('Enable or disable the local cache.<br/>
        Currently only ufs directory cache type is supported.<br/>
        <b class="text-danger">Do not enable on embedded systems with SD or CF cards as this may break your drive.</b>');
echo gettext('Enable or disable the proxy service.');
echo gettext('Enable or disable traffic management.');
echo gettext('Enable or disable verbose logging. Each log line turns into a much richer format.');
echo gettext('Enable promiscuous mode, for certain setups (like IPS with vlans), this is required to actually capture data on the physical interface.');
echo gettext('Enable protection mode (block traffic).<br />Before enabling, please disable all hardware offloading first <a href="/system_advanced_network.php">in advanced network</a>.');
echo gettext('Enable proxy');
echo gettext('Enable remote access');
echo gettext('Enable remote access to HAProxy\'s statistics page. <b>This may be a security risk if you do not enable authentication!</b> Note that you need to add appropiate firewall rules for this to work.');
echo gettext('Enable ruleset');
echo gettext('Enable scan images');
echo gettext('Enable store logging');
echo gettext('Enable store logging.');
echo gettext('Enable this Lua script.');
echo gettext('Enable this backend');
echo gettext('Enable this feature');
echo gettext('Enable this fingerprint rule.');
echo gettext('Enable this frontend');
echo gettext('Enable this zone');
echo gettext('Enable to log health check status updates.');
echo gettext('Enable traffic management.');
echo gettext('Enable transparent ftp proxy mode to forward all requests for destination port 21 to the proxy server without any additional configuration.');
echo gettext('Enabled');
echo gettext('Encode Username');
echo gettext('Enter a description to explain what this blacklist is intended for.');
echo gettext('Enter a description to explain what this job is intended for.');
echo gettext('Enter a filename for storing the blacklist.');
echo gettext('Enter a number followed by one of the supported suffixes "d" (days), "h" (hour), "m" (minute), "s" (seconds), "ms" (miliseconds). This configures the maximum duration of an entry in the stick-table since it was last created, refreshed or matched. The maximum duration is slightly above 24 days.');
echo gettext('Enter a number followed by one of the supported suffixes "k", "m", "g". This configures the maximum number of entries that can fit in the table. This value directly impacts memory usage. Count approximately 50 bytes per entry, plus the size of a string if any.');
echo gettext('Enter an url to fetch the blacklist from.');
echo gettext('Enter parameters for this job if required.');
echo gettext('Enter the allowed overall bandtwith in kilobits per second (leave empty to disable).');
echo gettext('Enter the allowed per host bandwidth in kilobits per second (leave empty to disable).');
echo gettext('Enter the cache memory size to use.');
echo gettext('Enter the days of the month for the job to act, can also be a comma separated list, * (each) or a range (ex. 1,20,28 or 1-28)');
echo gettext('Enter the days of the week for the job to act, can also be a comma separated list, * (each) or a range (ex. 1,2,3 or 1-3)');
echo gettext('Enter the hours for the job to act, can also be a comma separated list, * (each) or a range (ex. 10,11,12 or 10-12)');
echo gettext('Enter the maximum size (in MB) to use for SSL certificates.');
echo gettext('Enter the maxium size for downloads in kilobytes (leave empty to disable).');
echo gettext('Enter the maxium size for uploads in kilobytes (leave empty to disable).');
echo gettext('Enter the minutes for the job to act, can also be a comma separated list, * (each) or a range (ex. 10,20,30 or 10-30)');
echo gettext('Enter the months for the job to act, can also be a comma separated list, * (each) or a range (ex. 1,2,3 or 1-3)');
echo gettext('Enter the number of first-level subdirectories for the local cache (default is 16).');
echo gettext('Enter the number of first-level subdirectories for the local cache (default is 256).');
echo gettext('Enter the number of ssl certificate workers to use (sslcrtd_children).');
echo gettext('Enter the size of the preview which is sent to the ICAP server.');
echo gettext('Enter the storage size for the local cache (default is 100).');
echo gettext('Enter the url where the reqmod requests should be sent to.');
echo gettext('Enter the url where the respmod requests should be sent to.');
echo gettext('Error Files');
echo gettext('Error code');
echo gettext('Error files');
echo gettext('Expiration time');
echo gettext('Explicit Congestion Notification');
echo gettext('Expression');
echo gettext('FQ-CoDel flows');
echo gettext('FQ-CoDel limit');
echo gettext('FQ-CoDel quantum');
echo gettext('FQDN or IP');
echo gettext('FTP proxy interfaces');
echo gettext('FTP proxy port');
echo gettext('Filename');
echo gettext('Filter syslog level');
echo gettext('Filter to use when downloading this ruleset, applies this action to all incoming lines.');
echo gettext('Find value');
echo gettext('Form condition');
echo gettext('GeoIP/Country');
echo gettext('GeoIP/Direction');
echo gettext('Grant access to HAProxy statistics page. Please provide both user and password in clear text separated by a \':\', i.e. john:secret123 or jdoe:anonymous. Use TAB key to complete adding a user.');
echo gettext('Group Id');
echo gettext('HAProxy processes');
echo gettext('HTTP check options');
echo gettext('HTTP host');
echo gettext('HTTP method');
echo gettext('HTTP version');
echo gettext('Hard timeout (minutes)');
echo gettext('Health Checking');
echo gettext('Health check');
echo gettext('Health check buffer size');
echo gettext('Hostname');
echo gettext('Hostname (of this machine) to redirect login page to, leave blank to use this interface IP address, otherwise make sure the client can access DNS to resolve this location. When using a SSL certificate, make sure both this name and the cert name are equal.');
echo gettext('Hours');
echo gettext('ICP port');
echo gettext('IPS mode');
echo gettext('Idle timeout (minutes)');
echo gettext('If provided, all traffic will be transmitted over an HTTPS connection to protect against eavesdroppers.');
echo gettext('If set (default), Squid will include a Via header in requests and replies as required by RFC2616.');
echo gettext('If this checkbox is checked, you can use an ICAP server to filter or replace content.');
echo gettext('If this option is set, users can login on multiple machines at once. If disabled subsequent logins will cause machines previously logged in with the same username to be disconnected.');
echo gettext('If you enable this option, the client IP address will be sent to the ICAP server. This can be useful if you want to filter traffic based on IP addresses.');
echo gettext('If you enable this option, the username of the client will be sent to the ICAP server. This can be useful if you want to filter traffic based on usernames. Note, that authentication is required to use usernames.');
echo gettext('If you really need more performance, you can disable scanning of JPG, GIF and PNG files. These are probably the most common files around, so it will save lots of CPU. But be warned, image exploits exist and more could be found. Think twice if you want to disable!');
echo gettext('If you use previews, only a part of the data is sent to the ICAP server. Setting this option can improve the performance.');
echo gettext('Ignore hosts in access.log');
echo gettext('Indicates where to send the logs. Takes an IPv4 or IPv6 address optionally followed by a colon (\':\') and a UDP port, i.e. 127.0.0.1 or 10.0.0.1:514');
echo gettext('Input Filter');
echo gettext('Interfaces');
echo gettext('Internal number used for this zone');
echo gettext('Interval before dropping packets (in ms), leave empty for default');
echo gettext('Listen Addresses');
echo gettext('Local stats TCP port');
echo gettext('Log Host');
echo gettext('Log Status Changes');
echo gettext('Log target');
echo gettext('Logging Options');
echo gettext('Logical operator (for ACLs)');
echo gettext('Max. Connections');
echo gettext('Max. line length');
echo gettext('Maximum RAM per LUA process');
echo gettext('Maximum SSL DH Size');
echo gettext('Maximum connections');
echo gettext('Maximum download size (Kb)');
echo gettext('Maximum object size (MB)');
echo gettext('Maximum size scaned file (MB)');
echo gettext('Maximum upload size (Kb)');
echo gettext('Memory Cache size in Megabytes');
echo gettext('Message');
echo gettext('Minimum acceptable persistent queue delay (in ms), leave empty for default');
echo gettext('Minutes');
echo gettext('Mode');
echo gettext('Months');
echo gettext('NOTE: Define default parameters for ALL Frontends, Backends and Servers here. They may still be overriden elsewhere.');
echo gettext('NOTE: Define global parameters for the HAProxy service. They cannot be overriden.');
echo gettext('NOTE: You need to configure frontends, backends and servers before enabling HAProxy.');
echo gettext('Name');
echo gettext('Name to identify this ACL.');
echo gettext('Name to identify this Lua script.');
echo gettext('Name to identify this action.');
echo gettext('Name to identify this backend.');
echo gettext('Name to identify this error file.');
echo gettext('Name to identify this frontend.');
echo gettext('Name to identify this server.');
echo gettext('Name/Identifier');
echo gettext('Negate condition');
echo gettext('Non-HTTP check options');
echo gettext('Number of HAProxy processes to start.<br/><div class="text-info"><b>NOTE:</b> You may experience random issues in multi-process mode. For more information about the "nbproc" option please see the HAProxy Documentation.</div>');
echo gettext('Number of first-level subdirectories');
echo gettext('Number of logs to keep.');
echo gettext('Number of second-level subdirectories');
echo gettext('Option pass-through');
echo gettext('Optional parameters');
echo gettext('Overall bandwidth throttling (Kbps)');
echo gettext('Parameters');
echo gettext('Paste the content of your Lua script here.');
echo gettext('Paste the content of your errorfile here. The files should not exceed the configured buffer size, which generally is 8 or 16 kB.');
echo gettext('Pattern matcher');
echo gettext('Per host bandwidth throttling (Kbps)');
echo gettext('Port');
echo gettext('Port to check');
echo gettext('Preview Size');
echo gettext('Promiscuous mode');
echo gettext('Provide either the FQDN or the IP address of this server.');
echo gettext('Provide the TCP communication port for this server, i.e. 80 or 443.');
echo gettext('Provide the TCP communication port to use during check, i.e. 80 or 443.');
echo gettext('Proxy interfaces');
echo gettext('Proxy port');
echo gettext('Query Backend');
echo gettext('Raise Log Level');
echo gettext('Reference');
echo gettext('Remote listen addresses');
echo gettext('Request Modify URL');
echo gettext('Request URI');
echo gettext('Response Modify URL');
echo gettext('Retries');
echo gettext('Revision');
echo gettext('Rotate alert logs at provided interval.');
echo gettext('Rotate log');
echo gettext('Run as root');
echo gettext('SMTP domain');
echo gettext('SMTPHost');
echo gettext('SSL');
echo gettext('SSL Offloading');
echo gettext('SSL Proxy port');
echo gettext('SSL cache size');
echo gettext('SSL cert workers');
echo gettext('SSL certificate');
echo gettext('SSL no bump sites');
echo gettext('SSL/Fingerprint');
echo gettext('Save logs');
echo gettext('Scheduler type');
echo gettext('Select ACLs');
echo gettext('Select Authentication method');
echo gettext('Select HTTP method for health check.');
echo gettext('Select HTTP version for a HTTP health check.');
echo gettext('Select NetFlow version to use.');
echo gettext('Select authentication methods to use, leave empty for no authentication needed.');
echo gettext('Select certificates to use for SSL offloading. HAProxy\'s SNI recognition will determine the correct certificate automatically. If no SNI is provided by the client then the first certificate will be presented.<br/>To import additional certificates, go to <a href="/system_certmanager.php">Certificate Manager</a>.');
echo gettext('Select destinations to send NetFlow data to (ip address:port, eg 192.168.0.1:2550).');
echo gettext('Select health check expression.');
echo gettext('Select health check for servers in this backend.');
echo gettext('Select if job is enabled or not');
echo gettext('Select interface(s) the ftp proxy will bind to.');
echo gettext('Select interface(s) the proxy will bind to.');
echo gettext('Select interface(s) to enable NetFlow on.');
echo gettext('Select interface(s) to enable for captive portal.');
echo gettext('Select interface(s) to use. When enabling IPS, only use physical interfaces here (no vlans etc).');
echo gettext('Select interfaces used for WAN traffic to avoid counting NAT traffic twice.');
echo gettext('Select interval (in milliseconds) between two consecutive health checks.');
echo gettext('Select one ore more ACLs to be used as condition for this action.');
echo gettext('Select the command that needs to be executed at given time frame.');
echo gettext('Select the multi-pattern matcher algorithm to use.');
echo gettext('Select type of health check.');
echo gettext('Select what to do with URI that contain whitespaces.<br/>
            <div class="text-info"><b>NOTE:</b> the current Squid implementation of encode and chop violates
                RFC2616 by not using a 301 redirect after altering the URL.</div>');
echo gettext('Select what to do with X-Forwarded for header.');
echo gettext('Send Client IP');
echo gettext('Send Username');
echo gettext('Send log data to.');
echo gettext('Separate Statistics');
echo gettext('Sequence order');
echo gettext('Server Timeout');
echo gettext('Servers');
echo gettext('Service');
echo gettext('Session redistribution');
echo gettext('Set action to perform here, only used when in IPS mode.');
echo gettext('Set the default backend to use for this frontend.');
echo gettext('Set the maximum inactivity time (in milliseconds) on the client side.');
echo gettext('Set the maximum inactivity time (in milliseconds) on the server side.');
echo gettext('Set the maximum number of concurrent connections for this frontend.');
echo gettext('Set the maximum object size (default 4MB when left empty).');
echo gettext('Set the maximum time (in milliseconds) to wait for a connection attempt to a server to succeed.');
echo gettext('Set the number of retries to perform on a server after a connection failure (default is 3).');
echo gettext('Set the number of retries to perform on a server after a connection failure.');
echo gettext('Set the running mode or protocol for this frontend.');
echo gettext('Set the running mode or protocol of the backend. Usually the frontend and the backend are in the same mode.');
echo gettext('Set value');
echo gettext('Sets the interval (in milliseconds) for running health checks on the server.');
echo gettext('Sets the maximum amount of RAM in megabytes per process usable by Lua. By default it is zero which means unlimited. It is important to set a limit to ensure that a bug in a script will not result in the system running out of memory.');
echo gettext('Sets the maximum number of concurrent connections per HAProxy process.<br/><div class="text-info"><b>NOTE:</b> HAProxy will not be able to allocate enough memory if you set this value too high. Consider raising the settings for kern.maxfiles and kern.maxfilesperproc if you need to specify a non-default value.</div>');
echo gettext('Sets the maximum size of the Diffie-Hellman parameters used for generating the ephemeral/temporary Diffie-Hellman key in case of DHE key exchange (default is 1024).<br/><div class="text-info"><b>NOTE:</b> Higher values will increase the CPU load. For more information about the "tune.ssl.default-dh-param" option please see the HAProxy Documentation.</div>');
echo gettext('Sets the operation mode to use for this server.');
echo gettext('Sets the source address which will be used when connecting to the server(s).');
echo gettext('Sets the source address which will be used when connecting to the server.');
echo gettext('Signature Id');
echo gettext('Size');
echo gettext('Source');
echo gettext('Source IP');
echo gettext('Source address');
echo gettext('Source port');
echo gettext('Specify HTTP host to use for health check. Requires HTTP/1.1.');
echo gettext('Specify HTTP request URI for health check.');
echo gettext('Specify a value to match with the action.');
echo gettext('Specify a value to match with the expression.');
echo gettext('Specify a value to match with the expression. <br/><div class="text-info"><b>NOTE:</b> It is important to note that the responses will be limited to a certain size defined by the global "tune.chksize" option, which defaults to 16384 bytes.</div>');
echo gettext('Specify additional SSL parameters such as force-sslv3, force-tlsv10, force-tlsv11, force-tlsv12, no-sslv3, no-tlsv10, no-tlsv11, no-tlsv12, no-tls-tickets or customize the list of SSL ciphers.<br/>Example: no-sslv3 ciphers HIGH:!DSS:!aNULL@STRENGTH<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('Specify an optional maximum line length. Log lines larger than this value will be truncated before being sent. The reason is that syslog servers act differently on log line length. All servers support the default value of 1024, but some servers simply drop larger lines while others do log them.');
echo gettext('Specify the TCP port used for agent checks.');
echo gettext('Specify the URL parameter to be checked for the value specified below.<br/><b>Not used for any other expression.</b>');
echo gettext('Specify the domain name to present to the server for SMTP/ESMTP health checks.');
echo gettext('Specify the scheduling algorithm to use');
echo gettext('Specify the username to be used for database health checks.');
echo gettext('Spread checks');
echo gettext('Stats enabled');
echo gettext('Stats users');
echo gettext('Stick-table persistence');
echo gettext('Suppress Squid version string info in HTTP headers and HTML error pages.');
echo gettext('Suppress version string');
echo gettext('Syslog facility');
echo gettext('Table type');
echo gettext('Temporary file will grow only up to this size. This means scanner will scan data until this limit is reached. There are two sides to this setting. By limiting the size, you gain performance, less waiting for big files and less needed temporary space. But there is slightly higher chance of virus slipping through (though scanning large archives should not be gateways function, HAVP is more geared towards small exploit detection etc). VALUE IN MB!!!! 0 = No size limit');
echo gettext('Test type');
echo gettext('The HTTP status code.<br/><div class="text-info"><b>NOTE:</b> It is important to understand that errorfiles are NOT meant to rewrite errors returned by the server, but errors detected and returned by HAProxy. This is why the list of supported errors is limited to a small set.</div>');
echo gettext('The SSL fingerprint, for example "B5:E1:B3:70:5E:7C:FF:EB:92:C4:29:E5:5B:AC:2F:AE:70:17:E9:9E".');
echo gettext('The hard size limit of all queues managed by this instance, leave empty for defaults');
echo gettext('The header which should be used to send the username to the ICAP server.');
echo gettext('The maximum number of characters that will be stored in the stick table (if appropiate table type is selected).');
echo gettext('The number of bytes a queue can serve before being moved to the tail of old queues list (bytes), leave empty for defaults');
echo gettext('The number of flow queues that are created and managed, leave empty for defaults');
echo gettext('The port number where Squid sends and receives ICP queries to and from neighbor caches. Leave blank to disable (default). The standard UDP port for ICP is 3130.');
echo gettext('The port the proxy service will listen to.');
echo gettext('The port the ssl proxy service will listen to.');
echo gettext('The prompt will be displayed in the authentication request window.');
echo gettext('The total number of authenticator processes to spawn.');
echo gettext('These lines will be added to the HAProxy backend configuration.<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('These lines will be added to the HAProxy frontend configuration.<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('These lines will be added to the defaults settings of to the HAProxy configuration file.<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('These lines will be added to the global settings of to the HAProxy configuration file.<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('These lines will be added to the statistics settings of to the HAProxy configuration file.<br/><div class="text-info"><b>NOTE:</b> The syntax will not be checked, use at your own risk!</div>');
echo gettext('This is the email address displayed in error messages to the users.');
echo gettext('This is the hostname to be displayed in proxy server error messages.');
echo gettext('This option reverses the order of preference to make Squid contact dual-stack websites over IPv4 first.
            Squid will still perform both IPv6 and IPv4 DNS lookups before connecting.
            <div class="alert alert-warning"><b class="text-danger">Warning:</b> This option will restrict the situations under which IPv6
                connectivity is used (and tested). Hiding network problems
                which would otherwise be detected and warned about.</div>');
echo gettext('This specifies for how long (in hours) the proxy server assumes an externally validated username and password combination is valid (Time To Live).<br/>
            When the TTL expires, the user will be prompted for credentials again.');
echo gettext('Timestamp');
echo gettext('Total bandwidth for this pipe');
echo gettext('Tuning Options');
echo gettext('Type');
echo gettext('Type IP addresses you want to allow access to the proxy server, use a comma or press Enter for new item. <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Type IP addresses you want to deny access to the proxy server, use a comma or press Enter for new item. <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Type IPs of alternative DNS servers you like to use. <div class="text-info"><b>TIP: </b>You can also paste a comma seperated list into this field.</div>');
echo gettext('Type subnets you want to allow access to the proxy server, use a comma or press Enter for new item. <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Type subnets/addresses you want to ignore for the access.log <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('URL');
echo gettext('URL not scan');
echo gettext('URL not scaned');
echo gettext('URL parameter');
echo gettext('Unrestricted IP addresses');
echo gettext('Use Frontend port');
echo gettext('Use Via header');
echo gettext('Use alternate DNS-servers');
echo gettext('Use backend');
echo gettext('Use custom template package for user login');
echo gettext('Use server');
echo gettext('Use this backend if the condition is true.<br/><b>Not used for any other action.</b>');
echo gettext('Use this backend to count usable servers.<br/><b>Not used for any other expression.</b>');
echo gettext('Use this option if your usernames need to be encoded.');
echo gettext('Use this server if the condition is true.<br/><b>Not used for any other action.</b>');
echo gettext('Use this to invert the meaning of the expression.');
echo gettext('Username Header');
echo gettext('Value');
echo gettext('Version');
echo gettext('Visible Hostname');
echo gettext('Weight');
echo gettext('Weight of this queue (1..100), used to prioritize within a pipe. (1 is low, 100 is high)');
echo gettext('When enabled the subnets of the selected interfaces will be added to the allow access list.');
echo gettext('Whitelist');
echo gettext('Whitelist destination domains.<br/>
        You may use a regular expression, use a comma or press Enter for new item.<br/>
        <div class="alert alert-info">
            <b>Examples:</b><br/>
            <b class="text-primary">mydomain.com</b> -> matches on <b>*.mydomain.com</b><br/>
            <b class="text-primary">^https?:\/\/([a-zA-Z]+)\.mydomain\.</b> -> matches on <b>http(s)://textONLY.mydomain.*</b><br/>
            <b class="text-primary">\.gif$</b> -> matches on <b>\*.gif</b> but not on <b class="text-danger">\*.gif\test</b><br/>
            <b class="text-primary">\[0-9]+\.gif$</b> -> matches on <b>\123.gif</b> but not on <b class="text-danger">\test.gif</b><br/>
        </div>
        <div class="text-info"><b>TIP: </b>You can also paste a comma separated list into this field.</div>');
echo gettext('Whitespace handling of URI');
echo gettext('X-Forwarded for header handling');
echo gettext('X-Forwarded-For header');
echo gettext('Zone number');
echo gettext('bandwidth');
echo gettext('bandwidth Metric');
echo gettext('categories (if available)');
echo gettext('connected pipe for this queue');
echo gettext('description');
echo gettext('destination');
echo gettext('destination ip or network, examples 10.0.0.0/24, 10.0.0.1');
echo gettext('destination port number or well known name (imap,imaps, http,https,...)');
echo gettext('direction');
echo gettext('dst-port');
echo gettext('enable this pipe and it\'s related queues and rules');
echo gettext('enable this queue and it\'s related rules');
echo gettext('enabled');
echo gettext('interface');
echo gettext('interface 2');
echo gettext('ip address of the mail host');
echo gettext('mask');
echo gettext('matches incoming or outgoing packets or both (default)');
echo gettext('number of dynamic queues, leave empty for default');
echo gettext('order in which the rule will be evaluated (lowest first)');
echo gettext('pipe');
echo gettext('proto');
echo gettext('queue');
echo gettext('secondary interface, matches packets traveling to/from interface (1) to/from interface (2). can be combined with direction.');
echo gettext('select categories to use, leave empty for all. Categories are visible after initial download.');
echo gettext('sequence');
echo gettext('source');
echo gettext('source ip or network (netmask required), examples 10.0.0.0/24, 10.0.0.1/32');
echo gettext('source ip or network, examples 10.0.0.0/24, 10.0.0.1');
echo gettext('source port number or well known name (imap,imaps, http,https,...)');
echo gettext('src-port');
echo gettext('target');
echo gettext('target pipe or queue');
echo gettext('weight');
